# Generated by Django 4.2.2 on 2023-11-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=99999999, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=99999999, null=True),
                ),
                (
                    "languages",
                    models.CharField(blank=True, max_length=99999999, null=True),
                ),
                (
                    "frameworks",
                    models.CharField(blank=True, max_length=99999999, null=True),
                ),
                (
                    "image_url",
                    models.CharField(blank=True, max_length=99999999, null=True),
                ),
            ],
        ),
    ]
