# Generated by Django 4.2.2 on 2023-11-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("port1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(blank=True, max_length=99999999, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="facts",
            name="description",
            field=models.TextField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.TextField(blank=True, max_length=99999999, null=True),
        ),
    ]
